import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GNB from "./_components/gnb";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className="relative flex size-full min-h-screen flex-col bg-white group/design-root overflow-x-hidden"
          style={{ fontFamily: 'Manrope, "Noto Sans", sans-serif' }}
        >
          <div className="layout-container flex h-full grow flex-col">
            <GNB />
            {children}
            <footer className="flex justify-center">
              <div className="flex max-w-[960px] flex-1 flex-col">
                <footer className="flex flex-col gap-6 px-5 py-10 text-center @container">
                  <div className="flex flex-wrap items-center justify-center gap-6 @[480px]:flex-row @[480px]:justify-around">
                    <a
                      className="text-[#60758a] text-base font-normal leading-normal min-w-40"
                      href="#"
                    >
                      Terms of Service
                    </a>
                    <a
                      className="text-[#60758a] text-base font-normal leading-normal min-w-40"
                      href="#"
                    >
                      Privacy Policy
                    </a>
                    <a
                      className="text-[#60758a] text-base font-normal leading-normal min-w-40"
                      href="#"
                    >
                      Contact Us
                    </a>
                  </div>
                  <p className="text-[#60758a] text-base font-normal leading-normal">
                    @2024 Newsify. All rights reserved.
                  </p>
                </footer>
              </div>
            </footer>
          </div>
        </div>
      </body>
    </html>
  );
}
